# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e302ee869dfa36498c0b116aeafb78afa1e45795fc9466b10d368bd835ddee66e18ca73edae261d09c7961d0d8b0b76c4537d5bc799dbf3aeec16e77831c61e5

test:
  secret_key_base: ac73e591d6a59a613c15b8536bfbca276f1931b3f345eb64eaa2abffb4a86cd22613d4605242c28e2eedef840b44e72225ade628c8db91a50423f75743332b43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
